version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: go-rest-api:latest
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    restart: unless-stopped

  app-dev:
    image: golang:1.25
    working_dir: /src
    volumes:
      - ./:/src:cached
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    command: sh -c "go mod download && go run ."
    # use when you want to keep logs in the host
    # tty: true
